spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

#spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:27695/railway
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.tool.hbm2ddl=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.javaweb.filter.JwtTokenFilter=DEBUG

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR

#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.springframework.security.web.FilterChainProxy=DEBUG


server.jsp-servlet.init-parameters.development=false
spring.jpa.open-in-view=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.debug=true


server.servlet.context-path=/


#spring.data.redis.host=${REDISHOST}
#spring.data.redis.port=${REDISPORT}
#spring.data.redis.password=${REDISPASSWORD}
#spring.data.redis.username=${REDISUSER}
#spring.data.redis.timeout=30000

spring.data.redis.host=redis.railway.internal
spring.data.redis.port=6379
spring.data.redis.password=iKAHpQbSBdQSRYBCdBStgfBSYGiyDmoT
spring.data.redis.username=default

logging.level.org.springframework.security=ERROR
logging.level.org.springframework.security.web.FilterChainProxy=ERROR
logging.level.org.springframework.security.web.authentication=ERROR
logging.level.org.springframework.security.web.access=ERROR
logging.level.org.hibernate.tool.hbm2ddl=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=ERROR

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000 
spring.datasource.hikari.leak-detection-threshold=20000


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.jackson.time-zone=Asia/Ho_Chi_Minh
